service: sls-bgc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  memorySize: 512
  timeout: 30
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  cronScrapAmazon:
    handler: lambdas/schedulesTasks/cronScrapAmazon.handler
    events:
      - schedule: cron(1 21 * * ? *)
  getBestSellers:
    handler: lambdas/endpoints/getBestSellers.handler
    events:
      - http:
          path: bestSellers/{date}
          method: get
          cors: true

custom:
  tableName: bestSellers

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
