service: sls-bgc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  memorySize: 512
  timeout: 200

functions:
  handler:
    handler: index.handler
    description:
    runtime:
    memorySize: 512
    timeout: 200
    events:
