service: sls-bgc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  memorySize: 512
  timeout: 200

functions:
  getBestSellers:
    handler: lambdas/getBestSellers.handler
    events:
      - http:
          path: bestSellers
          method: get
          cors: true
